spring.application.name=Budgeting
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
supabase.service.key=${supabase.service.key}
supabase.jwt.x=${supabase.jwt.x}
supabase.jwt.y=${supabase.jwt.y}
supabase.project.url=${supabase.project.url}
spring.config.import=optional:classpath:application-local.properties